apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-nginx
  labels:
    app: portal-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-nginx
  template:
    metadata:
      labels:
        app: portal-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.23.0-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: portal-nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: portal-nginx-config
          configMap:
            name: portal-nginx-config
      imagePullSecrets:
        - name: portal-docker-pull-secret
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
